SAMPLE_RATE = 44_100
CHANNELS = 2
STEPS = 16
PATTERN_SCENES = 8

INSTRUMENTS = [
    "Kick",
    "Snare",
    "Closed Hat",
    "Open Hat",
    "Clap",
    "Low Tom",
    "Rim",
    "Perc",
]

DEFAULT_PATTERN = [
    "1000100010001000",
    "0000100000001000",
    "1010101010101010",
    "0000000010000000",
    "0000100000001000",
    "1000000010000000",
    "0010001000100010",
    "0001000000010000",
]

GENERATOR_STYLES = [
    "House",
    "Techno",
    "Rock",
    "Hip Hop",
    "Boom Bap",
    "Breakbeat",
    "UK Garage",
    "Jungle",
    "Drum & Bass",
    "Funk",
    "Trap",
    "Reggaeton",
    "Latin",
    "Disco",
    "Electro",
    "Synthwave",
    "Dark Synth",
    "Industrial",
    "IDM",
    "Minimal",
    "Dub",
    "Half-time",
]

SATURATION_MODES = ["Soft", "Hard", "Fold", "Sine"]
FILTER_TYPES = ["Off", "Low-pass", "High-pass", "Band-pass"]
LFO_SHAPES = ["Sine", "Triangle", "Square", "Random"]
LFO_DESTINATIONS = [
    "Pitch",
    "Filter Cutoff",
    "Pan",
    "Volume",
    "Drive",
    "Tone Level",
    "Noise Level",
    "Delay Send",
    "Reverb Send",
]
DRUM_PRESETS = {
    "Kick": {
        "tone_start": 104.0,
        "tone_end": 42.0,
        "tone_level": 1.08,
        "tone_decay": 0.74,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.030,
        "noise_decay": 0.040,
        "click_level": 0.055,
        "attack_ms": 0.45,
        "kick_mute": 0.14,
        "transient_attack": 0.10,
        "transient_body": 1.0,
        "drive": 0.12,
        "saturation_mode": "Soft",
        "filter_type": "Low-pass",
        "filter_cutoff": 1650.0,
        "filter_resonance": 0.06,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.25,
        "delay_feedback": 0.20,
        "delay_tone": 0.45,
        "delay_width": 0.55,
        "reverb_send": 0.0,
        "reverb_size": 0.28,
        "reverb_decay": 0.18,
        "reverb_tone": 0.42,
    },
    "Snare": {
        "tone_start": 205.0,
        "tone_end": 166.0,
        "tone_level": 0.36,
        "tone_decay": 0.16,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.78,
        "noise_decay": 0.24,
        "click_level": 0.11,
        "attack_ms": 0.45,
        "transient_attack": 0.12,
        "transient_body": 0.86,
        "drive": 0.10,
        "saturation_mode": "Soft",
        "filter_type": "High-pass",
        "filter_cutoff": 230.0,
        "filter_resonance": 0.08,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.25,
        "delay_feedback": 0.22,
        "delay_tone": 0.58,
        "delay_width": 0.70,
        "reverb_send": 0.0,
        "reverb_size": 0.32,
        "reverb_decay": 0.22,
        "reverb_tone": 0.54,
    },
    "Closed Hat": {
        "tone_start": 9200.0,
        "tone_end": 6100.0,
        "tone_level": 0.018,
        "tone_decay": 0.035,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.82,
        "noise_decay": 0.055,
        "click_level": 0.075,
        "attack_ms": 0.35,
        "transient_attack": 0.16,
        "transient_body": 0.78,
        "drive": 0.045,
        "saturation_mode": "Soft",
        "filter_type": "High-pass",
        "filter_cutoff": 6800.0,
        "filter_resonance": 0.06,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.20,
        "delay_feedback": 0.18,
        "delay_tone": 0.75,
        "delay_width": 0.70,
        "reverb_send": 0.0,
        "reverb_size": 0.24,
        "reverb_decay": 0.16,
        "reverb_tone": 0.72,
    },
    "Open Hat": {
        "tone_start": 8800.0,
        "tone_end": 5000.0,
        "tone_level": 0.022,
        "tone_decay": 0.19,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.92,
        "noise_decay": 0.34,
        "click_level": 0.085,
        "attack_ms": 0.45,
        "transient_attack": 0.12,
        "transient_body": 0.92,
        "drive": 0.040,
        "saturation_mode": "Soft",
        "filter_type": "High-pass",
        "filter_cutoff": 5400.0,
        "filter_resonance": 0.08,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.22,
        "delay_feedback": 0.18,
        "delay_tone": 0.72,
        "delay_width": 0.75,
        "reverb_send": 0.0,
        "reverb_size": 0.26,
        "reverb_decay": 0.20,
        "reverb_tone": 0.70,
    },
    "Crash": {
        "tone_start": 4700.0,
        "tone_end": 1450.0,
        "tone_level": 0.030,
        "tone_decay": 0.78,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.96,
        "noise_decay": 1.04,
        "click_level": 0.31,
        "attack_ms": 0.05,
        "transient_attack": 0.34,
        "transient_body": 0.94,
        "drive": 0.040,
        "saturation_mode": "Soft",
        "filter_type": "High-pass",
        "filter_cutoff": 620.0,
        "filter_resonance": 0.05,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.28,
        "delay_feedback": 0.18,
        "delay_tone": 0.60,
        "delay_width": 0.80,
        "reverb_send": 0.035,
        "reverb_size": 0.42,
        "reverb_decay": 0.28,
        "reverb_tone": 0.58,
    },
    "Clap": {
        "tone_start": 720.0,
        "tone_end": 460.0,
        "tone_level": 0.018,
        "tone_decay": 0.13,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.98,
        "noise_decay": 0.36,
        "click_level": 0.14,
        "attack_ms": 0.45,
        "transient_attack": 0.18,
        "transient_body": 0.86,
        "drive": 0.075,
        "saturation_mode": "Soft",
        "filter_type": "High-pass",
        "filter_cutoff": 1150.0,
        "filter_resonance": 0.08,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.24,
        "delay_feedback": 0.18,
        "delay_tone": 0.62,
        "delay_width": 0.75,
        "reverb_send": 0.0,
        "reverb_size": 0.32,
        "reverb_decay": 0.24,
        "reverb_tone": 0.58,
    },
    "Low Tom": {
        "tone_start": 170.0,
        "tone_end": 82.0,
        "tone_level": 0.96,
        "tone_decay": 0.40,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.060,
        "noise_decay": 0.050,
        "click_level": 0.060,
        "attack_ms": 0.45,
        "transient_attack": 0.10,
        "transient_body": 0.98,
        "drive": 0.070,
        "saturation_mode": "Soft",
        "filter_type": "Low-pass",
        "filter_cutoff": 1850.0,
        "filter_resonance": 0.08,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.24,
        "delay_feedback": 0.18,
        "delay_tone": 0.50,
        "delay_width": 0.60,
        "reverb_send": 0.0,
        "reverb_size": 0.30,
        "reverb_decay": 0.20,
        "reverb_tone": 0.46,
    },
    "Rim": {
        "tone_start": 1720.0,
        "tone_end": 2150.0,
        "tone_level": 0.56,
        "tone_decay": 0.052,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.42,
        "noise_decay": 0.038,
        "click_level": 0.18,
        "attack_ms": 0.10,
        "transient_attack": 0.20,
        "transient_body": 0.70,
        "drive": 0.075,
        "saturation_mode": "Soft",
        "filter_type": "Off",
        "filter_cutoff": 3200.0,
        "filter_resonance": 0.16,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.20,
        "delay_feedback": 0.16,
        "delay_tone": 0.64,
        "delay_width": 0.65,
        "reverb_send": 0.0,
        "reverb_size": 0.24,
        "reverb_decay": 0.16,
        "reverb_tone": 0.58,
    },
    "Perc": {
        "tone_start": 560.0,
        "tone_end": 285.0,
        "tone_level": 0.72,
        "tone_decay": 0.14,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.13,
        "noise_decay": 0.075,
        "click_level": 0.10,
        "attack_ms": 0.45,
        "transient_attack": 0.12,
        "transient_body": 0.86,
        "drive": 0.085,
        "saturation_mode": "Soft",
        "filter_type": "Band-pass",
        "filter_cutoff": 980.0,
        "filter_resonance": 0.22,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.22,
        "delay_feedback": 0.18,
        "delay_tone": 0.58,
        "delay_width": 0.66,
        "reverb_send": 0.0,
        "reverb_size": 0.26,
        "reverb_decay": 0.18,
        "reverb_tone": 0.52,
    },
}

DRUM_PRESET_NAMES = list(DRUM_PRESETS.keys())
