SAMPLE_RATE = 44_100
CHANNELS = 2
STEPS = 16
PATTERN_SCENES = 8

INSTRUMENTS = [
    "Kick",
    "Snare",
    "Closed Hat",
    "Open Hat",
    "Clap",
    "Low Tom",
    "Rim",
    "Perc",
]

DEFAULT_PATTERN = [
    "1000100010001000",
    "0000100000001000",
    "1010101010101010",
    "0000000010000000",
    "0000100000001000",
    "1000000010000000",
    "0010001000100010",
    "0001000000010000",
]

GENERATOR_STYLES = [
    "House",
    "Techno",
    "Rock",
    "Hip Hop",
    "Boom Bap",
    "Breakbeat",
    "UK Garage",
    "Jungle",
    "Drum & Bass",
    "Funk",
    "Trap",
    "Reggaeton",
    "Latin",
    "Disco",
    "Electro",
    "Synthwave",
    "Dark Synth",
    "Industrial",
    "IDM",
    "Minimal",
    "Dub",
    "Half-time",
]

SATURATION_MODES = ["Soft", "Hard", "Fold", "Sine"]
FILTER_TYPES = ["Off", "Low-pass", "High-pass", "Band-pass"]
LFO_SHAPES = ["Sine", "Triangle", "Square", "Random"]
LFO_DESTINATIONS = [
    "Pitch",
    "Filter Cutoff",
    "Pan",
    "Volume",
    "Drive",
    "Tone Level",
    "Noise Level",
    "Delay Send",
    "Reverb Send",
]
DRUM_PRESETS = {
    "Kick": {
        "tone_start": 132.0,
        "tone_end": 48.0,
        "tone_level": 1.08,
        "tone_decay": 0.46,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.045,
        "noise_decay": 0.050,
        "click_level": 0.12,
        "attack_ms": 0.12,
        "kick_mute": 0.04,
        "transient_attack": 0.24,
        "transient_body": 0.88,
        "drive": 0.16,
        "saturation_mode": "Soft",
        "filter_type": "Low-pass",
        "filter_cutoff": 2200.0,
        "filter_resonance": 0.08,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.25,
        "delay_feedback": 0.20,
        "delay_tone": 0.45,
        "delay_width": 0.55,
        "reverb_send": 0.0,
        "reverb_size": 0.28,
        "reverb_decay": 0.18,
        "reverb_tone": 0.42,
    },
    "Snare": {
        "tone_start": 265.0,
        "tone_end": 190.0,
        "tone_level": 0.50,
        "tone_decay": 0.20,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.92,
        "noise_decay": 0.24,
        "click_level": 0.17,
        "attack_ms": 0.12,
        "transient_attack": 0.24,
        "transient_body": 0.84,
        "drive": 0.14,
        "saturation_mode": "Soft",
        "filter_type": "High-pass",
        "filter_cutoff": 260.0,
        "filter_resonance": 0.10,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.25,
        "delay_feedback": 0.22,
        "delay_tone": 0.58,
        "delay_width": 0.70,
        "reverb_send": 0.0,
        "reverb_size": 0.32,
        "reverb_decay": 0.22,
        "reverb_tone": 0.54,
    },
    "Closed Hat": {
        "tone_start": 11200.0,
        "tone_end": 8200.0,
        "tone_level": 0.030,
        "tone_decay": 0.040,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.86,
        "noise_decay": 0.060,
        "click_level": 0.12,
        "attack_ms": 0.08,
        "transient_attack": 0.28,
        "transient_body": 0.70,
        "drive": 0.050,
        "saturation_mode": "Soft",
        "filter_type": "High-pass",
        "filter_cutoff": 7800.0,
        "filter_resonance": 0.04,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.20,
        "delay_feedback": 0.18,
        "delay_tone": 0.75,
        "delay_width": 0.70,
        "reverb_send": 0.0,
        "reverb_size": 0.24,
        "reverb_decay": 0.16,
        "reverb_tone": 0.72,
    },
    "Open Hat": {
        "tone_start": 10500.0,
        "tone_end": 6900.0,
        "tone_level": 0.034,
        "tone_decay": 0.30,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.94,
        "noise_decay": 0.40,
        "click_level": 0.11,
        "attack_ms": 0.08,
        "transient_attack": 0.20,
        "transient_body": 0.86,
        "drive": 0.045,
        "saturation_mode": "Soft",
        "filter_type": "High-pass",
        "filter_cutoff": 6500.0,
        "filter_resonance": 0.05,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.22,
        "delay_feedback": 0.18,
        "delay_tone": 0.72,
        "delay_width": 0.75,
        "reverb_send": 0.0,
        "reverb_size": 0.26,
        "reverb_decay": 0.20,
        "reverb_tone": 0.70,
    },
    "Crash": {
        "tone_start": 8200.0,
        "tone_end": 3000.0,
        "tone_level": 0.040,
        "tone_decay": 0.62,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.96,
        "noise_decay": 0.78,
        "click_level": 0.24,
        "attack_ms": 0.06,
        "transient_attack": 0.28,
        "transient_body": 0.88,
        "drive": 0.040,
        "saturation_mode": "Soft",
        "filter_type": "High-pass",
        "filter_cutoff": 3100.0,
        "filter_resonance": 0.04,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.28,
        "delay_feedback": 0.18,
        "delay_tone": 0.60,
        "delay_width": 0.80,
        "reverb_send": 0.010,
        "reverb_size": 0.24,
        "reverb_decay": 0.14,
        "reverb_tone": 0.68,
    },
    "Clap": {
        "tone_start": 920.0,
        "tone_end": 600.0,
        "tone_level": 0.020,
        "tone_decay": 0.12,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 1.00,
        "noise_decay": 0.34,
        "click_level": 0.16,
        "attack_ms": 0.10,
        "transient_attack": 0.30,
        "transient_body": 0.78,
        "drive": 0.070,
        "saturation_mode": "Soft",
        "filter_type": "High-pass",
        "filter_cutoff": 1250.0,
        "filter_resonance": 0.06,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.24,
        "delay_feedback": 0.18,
        "delay_tone": 0.62,
        "delay_width": 0.75,
        "reverb_send": 0.0,
        "reverb_size": 0.32,
        "reverb_decay": 0.24,
        "reverb_tone": 0.58,
    },
    "Low Tom": {
        "tone_start": 220.0,
        "tone_end": 104.0,
        "tone_level": 1.00,
        "tone_decay": 0.42,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.050,
        "noise_decay": 0.045,
        "click_level": 0.060,
        "attack_ms": 0.14,
        "transient_attack": 0.16,
        "transient_body": 0.92,
        "drive": 0.070,
        "saturation_mode": "Soft",
        "filter_type": "Low-pass",
        "filter_cutoff": 2100.0,
        "filter_resonance": 0.08,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.24,
        "delay_feedback": 0.18,
        "delay_tone": 0.50,
        "delay_width": 0.60,
        "reverb_send": 0.0,
        "reverb_size": 0.30,
        "reverb_decay": 0.20,
        "reverb_tone": 0.46,
    },
    "Rim": {
        "tone_start": 1850.0,
        "tone_end": 2850.0,
        "tone_level": 0.72,
        "tone_decay": 0.048,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.34,
        "noise_decay": 0.035,
        "click_level": 0.20,
        "attack_ms": 0.04,
        "transient_attack": 0.32,
        "transient_body": 0.60,
        "drive": 0.10,
        "saturation_mode": "Soft",
        "filter_type": "Band-pass",
        "filter_cutoff": 3400.0,
        "filter_resonance": 0.20,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.20,
        "delay_feedback": 0.16,
        "delay_tone": 0.64,
        "delay_width": 0.65,
        "reverb_send": 0.0,
        "reverb_size": 0.24,
        "reverb_decay": 0.16,
        "reverb_tone": 0.58,
    },
    "Perc": {
        "tone_start": 1280.0,
        "tone_end": 2460.0,
        "tone_level": 0.82,
        "tone_decay": 0.36,
        "pitch_env_amount": 0.0,
        "pitch_env_decay": 0.075,
        "noise_level": 0.32,
        "noise_decay": 0.18,
        "click_level": 0.12,
        "attack_ms": 0.06,
        "transient_attack": 0.18,
        "transient_body": 0.86,
        "drive": 0.050,
        "saturation_mode": "Soft",
        "filter_type": "Band-pass",
        "filter_cutoff": 4800.0,
        "filter_resonance": 0.12,
        "bit_depth": 16,
        "sample_rate_reduction": 1,
        "delay_send": 0.0,
        "delay_time": 0.22,
        "delay_feedback": 0.18,
        "delay_tone": 0.58,
        "delay_width": 0.66,
        "reverb_send": 0.0,
        "reverb_size": 0.26,
        "reverb_decay": 0.18,
        "reverb_tone": 0.52,
    },
}

DRUM_PRESET_NAMES = list(DRUM_PRESETS.keys())
