CONTROL_TOOLTIPS = {
    "play": "Start or pause the current pattern playback.",
    "stop": "Stop playback and reset the playhead to step 1.",
    "bpm": "Set the project tempo in beats per minute.",
    "swing": "Shift alternating 16th notes for a looser groove.",
    "master_volume": "Set the final output level before the audio device.",
    "output_meter": "Shows the final output spectrum after master processing.",
    "default_pattern": "Load the default drum pattern into the current scene.",
    "clear_pattern": "Clear all steps in the current scene.",
    "random_pattern": "Generate a new random pattern for the current scene.",
    "save_patch": "Save the full project as JSON, including sounds, scenes, globals, and Song Mode.",
    "load_patch": "Load a saved JSON project or legacy text pattern.",
    "export_pattern": "Render the current pattern scene as a 4-bar WAV loop.",
    "export_song": "Render the Song Mode chain once as a WAV file.",
    "scene_button": "Switch to this pattern scene. Scenes store step data, velocity, probability, ratchets, and track lengths.",
    "store_scene": "Store the current pattern data into the selected scene.",
    "copy_scene": "Copy the current scene pattern data.",
    "paste_scene": "Paste copied scene pattern data into the current scene.",
    "clear_scene": "Clear all tracks in the current scene.",
    "clear_all_patterns": "Clear every pattern scene while keeping track sounds and scene names.",
    "scene_name": "Name the current scene for easier arranging and morphing.",
    "sequencer_mute": "Mute or unmute this track directly from the sequencer row.",
    "pattern_pack": "Choose a factory groove to load into the current scene.",
    "apply_pattern_pack": "Load the selected groove into the current scene and apply its suggested tempo.",
    "apply_pattern_pack_with_kit": "Load the selected groove, suggested tempo, and matching factory kit pack.",
    "pattern_track": "Choose which track the copy, paste, clear, and rotate tools edit.",
    "copy_track": "Copy the selected track pattern and step expression data.",
    "paste_track": "Paste copied track pattern data into the selected track.",
    "clear_track": "Clear the selected track pattern and reset its step expression values.",
    "rotate_left": "Shift the selected track pattern one step earlier.",
    "rotate_right": "Shift the selected track pattern one step later.",
    "morph_source": "Choose the scene used as the starting point for pattern morphing.",
    "morph_target": "Choose the scene used as the destination feel for pattern morphing.",
    "morph_destination": "Choose the scene that will be overwritten with the morphed pattern.",
    "morph_amount": "Blend from the source scene toward the target scene. Step activity, velocity, probability, ratchets, and track length are morphed.",
    "apply_morph": "Write the morphed pattern into the selected write scene and switch to it.",
    "morph_summary": "Shows the current pattern morph route.",
    "song_play": "Start Song Mode playback from the active song slot.",
    "song_loop": "Repeat the song chain after the final slot finishes.",
    "song_add": "Add the current scene as a new song slot.",
    "song_position": "Shows the currently playing song slot and bar progress.",
    "song_scene": "Choose which pattern scene this song slot plays.",
    "song_bars": "Choose how many bars this song slot lasts before advancing.",
    "song_up": "Move this song slot one position earlier.",
    "song_down": "Move this song slot one position later.",
    "song_remove": "Remove this song slot from the arrangement.",
    "generate_session": "Create static pattern scenes and a Song Mode arrangement using the generator controls.",
    "generate_patterns": "Set how many pattern scenes the generator writes.",
    "generate_bars": "Set how many bars each generated song slot plays.",
    "generate_style": "Choose the broad groove template used for generated patterns.",
    "generate_complexity": "Control how busy the generated drum patterns are.",
    "generate_fills": "Control how many end-of-section fills and ratchets are written.",
    "generate_variation": "Control how much each generated scene differs from the base groove.",
    "fill_enabled": "Add subtle end-of-bar percussion and hat variations without changing the saved pattern.",
    "kit_pack": "Choose a factory kit flavor to apply to this track.",
    "apply_kit_pack": "Apply the selected factory kit flavor to this track only.",
    "track_preset": "Choose the drum preset used when Apply Preset is pressed.",
    "apply_preset": "Replace this track's sound settings with the selected drum preset.",
    "save_track_preset": "Save this track's sound design as a reusable JSON preset.",
    "load_track_preset": "Load a saved track sound preset without changing the pattern.",
    "audition": "Trigger this track once so you can hear the current patch.",
    "mute": "Mute this track unless it is soloed.",
    "solo": "Solo this track and silence tracks that are not soloed.",
    "envelope_editor": "Drag the four points to shape the one-shot modulation envelope over the drum hit.",
    "edit_step": "Choose the step edited by the Step Expression controls.",
    "step_velocity": "Set the selected step's hit level.",
    "step_probability": "Set the selected step's chance of triggering.",
    "step_ratchet": "Repeat the selected step multiple times within its step duration.",
    "step_bass_note": "Set this step's note override. C2 clears the override and returns the step to the base patch pitch.",
    "inspector_active": "Turn the selected sequencer step on or off.",
    "inspector_audition": "Audition the selected track once.",
    "inspector_edit_sound": "Jump to this track's sound-design tab.",
}


PARAM_TOOLTIPS = {
    "global_filter_cutoff": "Set the master low-pass filter cutoff for the full mix.",
    "global_filter_resonance": "Add emphasis around the master filter cutoff.",
    "global_drive": "Add master bus saturation after the global filter.",
    "compressor_amount": "Control how strongly the master bus compressor shapes the mix.",
    "global_fx_amount": "Scale all per-patch delay and reverb sends globally.",
    "global_density": "Scale step probability globally for thinner or busier playback.",
    "global_humanize": "Randomly vary hit velocity for a less rigid groove.",
    "volume": "Set this track's patch output level.",
    "decay": "Scale the overall length of this drum hit.",
    "pitch": "Transpose this drum patch up or down.",
    "drive": "Add saturation to this drum patch.",
    "pan": "Place this track in the stereo field.",
    "transient_attack": "Boost or soften the initial transient of this drum hit.",
    "transient_body": "Adjust the body level after the transient.",
    "track_steps": "Set this track's loop length from 1 to 16 steps.",
    "tone_level": "Set the pitched oscillator level.",
    "noise_level": "Set the noise generator level.",
    "click_level": "Set the short click/transient layer level.",
    "kick_mute": "Dampen kick drum resonance like adding a blanket or pillow inside the shell.",
    "filter_resonance": "Add emphasis around this patch's filter cutoff.",
    "saturation_mode": "Choose the saturation curve used by this patch.",
    "attack_ms": "Set the fade-in time at the start of the drum hit.",
    "bit_depth": "Lower this value for bit-crushed digital grit.",
    "sample_rate_reduction": "Increase this value for sample-rate reduction grit.",
    "bass_enabled": "Make this track follow its per-step notes instead of using one fixed pitch.",
    "filter_type": "Choose the patch filter type.",
    "filter_cutoff": "Set the patch filter cutoff frequency.",
    "tone_start": "Set the starting frequency of the pitched tone sweep.",
    "tone_end": "Set the ending frequency of the pitched tone sweep.",
    "tone_decay": "Set how quickly the pitched tone fades.",
    "noise_decay": "Set how quickly the noise layer fades.",
    "pitch_env_amount": "Set the pitch envelope depth in semitones.",
    "pitch_env_decay": "Set how quickly the pitch envelope returns.",
    "delay_send": "Send this patch into its delay effect.",
    "delay_feedback": "Set how much delayed signal repeats.",
    "delay_tone": "Darken or brighten the delay repeats.",
    "delay_width": "Set the stereo width of the delay repeats.",
    "reverb_send": "Send this patch into its reverb effect.",
    "reverb_size": "Set the perceived reverb space size.",
    "reverb_decay": "Set how long the reverb tail lasts.",
    "reverb_tone": "Darken or brighten the reverb tail.",
    "delay_time": "Set the delay repeat time in seconds.",
    "lfo_enabled": "Enable LFO 1 for this patch.",
    "lfo_shape": "Choose LFO 1's waveform.",
    "lfo_destination": "Choose the parameter LFO 1 modulates.",
    "lfo_rate": "Set LFO 1 speed in Hz.",
    "lfo_phase": "Set LFO 1's starting phase inside each hit.",
    "lfo_amount": "Set LFO 1 modulation depth.",
    "lfo2_enabled": "Enable LFO 2 for this patch.",
    "lfo2_shape": "Choose LFO 2's waveform.",
    "lfo2_destination": "Choose the parameter LFO 2 modulates.",
    "lfo2_rate": "Set LFO 2 speed in Hz.",
    "lfo2_phase": "Set LFO 2's starting phase inside each hit.",
    "lfo2_amount": "Set LFO 2 modulation depth.",
    "env_mod_enabled": "Enable the one-shot modulation envelope for this patch.",
    "env_mod_destination": "Choose the parameter controlled by the modulation envelope.",
    "env_mod_amount": "Set envelope modulation depth. Negative values invert the envelope.",
}

